name: Use App token
description: Run GitHub Actions as a GitHub App by using the app's authentication token.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  app_id:
    description: The ID of the GitHub App.
    required: false
  private_key:
    description: The private key of the GitHub App (can be Base64 encoded).
    required: false
  fallback:
    description: The fallback token when bot token generate failed.
    required: false
  variable_name:
    description: The name of generated token in exported environment variable.
    required: false
  env_name:
    description: The name of generated token in exported environment variable.
    required: false
  secret_name:
    description: The secret name created on current repository.
    required: false
  clean_secret:
    description: Should clean the secret or not when this action run completed.
    required: false
    default: false

outputs:
  token:
    description: The token for the GitHub App on the current repository.

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js

branding:
  icon: anchor
  color: orange # gray-dark purple red orange green blue yellow black white
